Release Docs Improvements
SciTools/iris pull request #3895
Opened 2020-09-30 16:06 UTC by trexfeathers

## 🚀 Pull Request

### Description

Some changes to the release documentation, identified while working through the Iris 3.0 release process.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2020-09-30 16:07 UTC, trexfeathers commented
@bjlittle feel free to either review+merge, or come back and add your own notes when convenient.

2020-10-12 07:41 UTC, bjlittle requested changes
@trexfeathers Awesome.

Could you target the `v3.0.x` branch instead of `master`, thanks :+1:

2020-10-12 08:18 UTC, trexfeathers commented
> Could you target the v3.0.x branch instead of master, thanks

OK @bjlittle, have done so

2020-10-12 08:20 UTC, bjlittle approved these changes

2020-10-12 08:22 UTC, merged