Test string argument to remove ancilliary variable
SciTools/iris pull request #3931
Opened 2020-11-27 17:04 UTC by gcaria

## 🚀 Pull Request

### Description
Resolves #3602 

I have just started to work on this, and after adding a short test I get 5 failures when testing `lib/iris/tests/unit/cube/test_Cube.py`, all `AssertionError`s similar to:
```
AssertionError: CML do not match: /home/gcaria/github/iris/lib/iris/tests/results/unit/cube/Cube/xml/checksum_ignores_masked_values.cml
```

which don't seem to be related to the test I've added. I've followed the instructions for [running the tests](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_running_tests.html) so I'm not sure what I'm missing.

2020-11-27 19:09 UTC, rcomer commented
Hi @gcaria, thanks for the contribution!  I’m not sure about that specific error, but I can see that your branch is a couple of commits behind the master branch.   The most recent commit to master incorporates a switch from Travis-CI to Cirrus-CI to run the tests within the PR.  So I suggest rebasing to pick up that change, and then we can see your test output here.  So something like:

```
git fetch upstream
git rebase upstream/master
git push -f origin
```

2020-11-27 19:30 UTC, rcomer commented
Depending how and exactly when you created your python environment, it may be also be worth worth re-doing that.  cftime v1.3 was recently released, and caused all sorts of failures within Iris.  We’ve temporarily pinned the cftime version (#3927), but that was also after you created your branch.

So if you rebase, then create a new environment [from the source](https://scitools-iris.readthedocs.io/en/latest/installing.html#installing-from-source-devs), then run the tests again, you _might_ get a different result.

2020-12-01 15:43 UTC, gcaria commented
Thanks @rcomer for the useful feedback !

In addition to changing the `cftime` version, I've also switched to python3.7 (was using 3.8 before) which was surely part of the problem, at least locally. Now everything works :)

I see that in #3295 the docstring for the `remove_cell_measure` was also expanded.

Would it be appropriate to have the same also for the modified methods of this PR ?

2020-12-01 16:10 UTC, rcomer commented
Hi @gcaria, glad you got the tests working!  I don't think I'm the best person to advise on this specific change as I haven't done anything with this part of the code.  Looks like @stephenworsley has done a lot in this area so hopefully he can advise.

2020-12-02 15:22 UTC, bjlittle requested changes
@gcaria Awesome contribution! Thanks for taking the time to push this fix to `iris`. Much appreciated :smile: 

Could I ask you to also make a `whatsnew` entry to accompany this pull-request?

Simply make the following addition to the `<root-dir>/docs/iris/src/whatsnew/latest.rst` file, under the section "🐛 Bugs Fixed", with something along the lines of:
```
* `@gcaria`_ fixed :meth:`~iris.cube.Cube.cell_measure_dims` to also accept the string name of a :class:`~iris.coords.CellMeasure`. (:pull:`3931`)
* `@gcaria`_ fixed :meth:`~iris.cube.Cube.ancillary_variable_dims` to also accept the string name of a :class:`~iris.coords.AncillaryVariable`. (:pull:`3931`)
```
Also, at the end of the `latest.rst` file add the following entry:
```
.. _@gcaria: https://github.com/gcaria
```
Then we'll be good to go! :+1:

2020-12-05 13:03 UTC, gcaria commented
Oh I see this was all documented [here](https://scitools-iris.readthedocs.io/en/latest/developers_guide/documenting/whats_new_contributions.html), my bad for missing it !

2020-12-07 08:55 UTC, bjlittle commented
@gcaria Perfect, thanks :+1:

2020-12-07 08:56 UTC, bjlittle approved these changes

2020-12-07 08:56 UTC, merged