add mesh public doc-strings
SciTools/iris pull request #4037
Opened 2021-02-26 00:40 UTC by bjlittle

## 🚀 Pull Request

### Description

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2021-02-26 13:22 UTC, trexfeathers requested changes
Thanks @bjlittle!

These docstrings are clear, informative and appropriately mirror phrasing in the [UGRID conventions](https://ugrid-conventions.github.io/ugrid-conventions/).

I've picked up on some corrections that are needed.

As mentioned in specific comments on the code, I have trouble with the level of repetition between the filter methods, their singular equivalents and the remove methods. As I read/scroll through the rendered docs this repetition makes it much harder to keep my place. I like the pattern currently used for documenting `Cube.coord()` as a solution.

2021-02-26 13:22 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +
No `axis` for this one.

But it **does** need `cf_role` instead.

2021-02-26 13:22 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +        ``None``.
```suggestion
        Reset the name(s) used for the netCDF variable(s)
        representing the ``node``, ``edge`` and/or ``face`` dimension(s)
        to their default values.
```

2021-02-26 13:22 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +            Clear the name of the ``node`` dimension if ``True``. Default
```suggestion
            Reset the name of the ``node`` dimension if ``True``. Default
```

2021-02-26 13:22 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +            Clear the name of the ``edge`` dimension if ``True``. Default
```suggestion
            Reset the name of the ``edge`` dimension if ``True``. Default
```

2021-02-26 13:22 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +            Clear the name of the ``face`` dimension if ``True``. Default
```suggestion
            Reset the name of the ``face`` dimension if ``True``. Default
```

2021-02-26 13:22 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +        the ``node``, ``edge`` and ``face`` dimension.
```suggestion
        Assign the name(s) to be used for the netCDF variable(s) representing
        the ``node``, ``edge`` and ``face`` dimension(s).
```

2021-03-01 08:03 UTC, bjlittle commented on lib/iris/experimental/ugrid.py
> +            for Fortran and legacy netCDF files).
It's refered inconsistently through out Iris, typically I refer to it as `NetCDF`, but corrected it to the most common usage in the file... think I might stick to that, as it is a bugbear...

2021-03-01 08:58 UTC, bjlittle commented on lib/iris/experimental/ugrid.py
> +        All the :class:`Connectivity` coordinates of the :class:`Mesh`.
Me too, so I changed this :+1:

2021-03-01 10:39 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +        All the :class:`Connectivity` coordinates of the :class:`Mesh`.
I don't follow; it still says "`Connectivity` **coordinates**"? I don't mind if we keep it this way, but it sounds like you're saying you changed it? Am I missing some of your changes?

2021-03-01 10:54 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +
I'm inferring from the change that you are "definitely not in favour", as I put it. Could you do me the courtesy of explaining your reasoning? I see the current state as significantly difficult to read and maintain, but I'm assuming there's a good reason behind it?

2021-03-01 11:00 UTC, bjlittle commented on lib/iris/experimental/ugrid.py
> +
Yes, if as a user I click a link I want all the information I need, not a reference to another link.

We originally done that as a convenience to ourselves as maintainers and not the user. The docs are user centric, so being explicit is better.

2021-03-01 11:07 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +
OK that makes sense. I had been viewing this as a user reading an RTD webpage but of course that's only half the story. I certainly get as frustrated as anyone with Matplotlib's ubiquitous stub docstrings with `*args, **kwargs`!

2021-03-01 11:27 UTC, trexfeathers requested changes
Thanks for the latest clarifications @bjlittle. Here are some final requests in light of my improved understanding. Once these are addressed I'll be delighted to merge 😊

2021-03-01 11:27 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +#: Namedtuple for 1D mesh :class:`Connectivity` coordinates.
```suggestion
#: Namedtuple for 1D mesh :class:`Connectivity` instances.
```

2021-03-01 11:27 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +#: Namedtuple for 2D mesh :class:`Connectivity` coordinates.
```suggestion
#: Namedtuple for 2D mesh :class:`Connectivity` instances.
```

2021-03-01 11:27 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +            The CF standard name of the desired :class:`Connectibity`. If
```suggestion
            The CF standard name of the desired :class:`Connectivity`. If
```

2021-03-01 11:27 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +        Kwargs:
Need to remove the word `coordinate` by replicating the Kwarg descriptions you used for `Mesh.connectivities()` and `Mesh.connectivity()`.

2021-03-01 11:27 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +            :meth:`Cube.connectivities` for matching zero or more connectivities.
```suggestion
            :meth:`Mesh.connectivities` for matching zero or more connectivities.
```

2021-03-01 11:27 UTC, trexfeathers commented on lib/iris/experimental/ugrid.py
> +            :meth:`Cube.coords` for matching zero or more coordinates.
```suggestion
            :meth:`Mesh.coords` for matching zero or more coordinates.
```

2021-03-01 13:09 UTC, bjlittle commented on lib/iris/experimental/ugrid.py
> +
It is true that some people read the API docs end-to-end... I must admit I do do that sometimes, and it makes for a pretty disjointed read, as normally users dip into the API docs to look at a single specific thing.

So yeah, I get your point that this is overly verbose, but generally I think that's actually okay.

2021-03-01 14:13 UTC, trexfeathers commented
Amazing work as usual @bjlittle, LGTM

2021-03-01 14:13 UTC, merged

2021-03-01 14:22 UTC, bjlittle commented
@trexfeathers Hallelujah :100: :rocket: :partying_face: 

Thanks for sticking with it :beers: