Allow comparison with numpy array or list of len = 1.
SciTools/iris pull request #4083
Opened 2021-04-07 18:30 UTC by gcaria

Fixes #2914.

A simple fix to allow numpy arrays (or lists) with only element to be compared to Cell.

2021-06-04 14:30 UTC, rcomer requested changes
Hi @gcaria thanks for this and sorry nobody looked at it sooner.  Your solution looks great for length 1 lists and arrays, but I'm afraid it doesn't quite address the case from #2914, as that involved a zero dimensioned array:

```python
b = np.array(1.5)
len(b)
```
gives
```
TypeError: len() of unsized object
```

An alternative solution for numpy arrays might be to check `other.size` and use `other.item()` to get the value out.  Or you might come up with a better idea - I don't want to be prescriptive!

It would also be good to add some simple tests to [Test___common_cmp__](https://github.com/SciTools/iris/blob/d0eab4f0c2e212ccee8b42f830dd6991629dbae2/lib/iris/tests/unit/coords/test_Cell.py#L22) as a very basic check that you get the answer you expect for cases you have addressed (e.g. the example in #2914 should produce `False`).

Finally, it looks like the tests didn't actually run when you opened this PR.  There has been a lot of effort since then to fix our testing infrastructure.  So hopefully if you rebase it will get everything working sensibly again.

Again, thanks for the contribution!

2021-07-16 13:35 UTC, gcaria reviewed
Thanks for your feedback @rcomer! 

I have edited the code to take care of arrays such as `np.array(0)`, although it is arguably a bit of a misuse to not feed a sequence to `np.array`.

More than happy to add tests too, just wanted to check first if the casting to `float` sounds like a good idea (since the operations are `<, >, <=, >=` it seems fine to me).

2021-07-16 14:51 UTC, rcomer commented
Thanks for the update @gcaria!

>  it is arguably a bit of a misuse to not feed a sequence to np.array

I don't know how the original issue came up and unfortunately the developers involved have both since moved on.  However I've found a couple of ways the 0-dimensional array could be created:

```python
cube  = iris.cube.Cube(1)
print(repr(cube.data))

array = np.squeeze([[[4]]])
print(repr(array))
```

gives
```
array(1)
array(4)
```
so possibly there was a use-case where the 0-dimensional array came out of some other calculation.

Using `float` seems OK to me too given the operators.

2021-07-18 21:40 UTC, gcaria commented
Thanks for the clarification @rcomer, I was mostly surprised to see `np.array` can be used in that way, but this is surely not an issue with `iris`.

I have added a minimal set of lines for the testing.

2021-07-19 08:38 UTC, rcomer commented
Thanks @gcaria, these tests look good to me.  Could you add similar tests for the size 1 array/list case you originally added?  Just to make sure the various paths through the `if` loop are covered.  Then this just needs an entry under ["bugs fixed" in the whatsnew](https://github.com/SciTools/iris/blob/main/docs/src/whatsnew/latest.rst#-bugs-fixed) and I think we're done.

Really appreciate your work on this - it's great to get some of these old issues tidied up!

2021-07-23 07:02 UTC, rcomer approved these changes
Great; thanks @gcaria!

2021-07-23 07:03 UTC, merged