Add a method to return a CubeList from CubeList.copy()
SciTools/iris pull request #4094
Opened 2021-04-09 17:33 UTC by Badboy-16

🚀 Pull Request

### Description
I had a go to resolve issue #4066 .
A method copy() was created in the CubeList class to return a CubeList object instead of a list.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2021-05-19 09:30 UTC, trexfeathers commented
Hi @Badboy-16 ,  thanks for raising this - **we really appreciate our users becoming collaborators** 🙂. And sorry for our absence on this - we've been away on some intense project work!

Your solution looks ideal 🍻, but as mentioned in the [pull request checklist](https://scitools-iris.readthedocs.io/en/stable/developers_guide/contributing_pull_request_checklist.html) we will also need [an entry in What's New](https://scitools-iris.readthedocs.io/en/stable/developers_guide/documenting/whats_new_contributions.html#whats-new-contributions).

I also think it would be sensible to add a test confirming this is working as expected. If you'd like any help with this just shout.

Unfortunately in April we had some continuous integration issues, which we have since fixed - to bring in these fixes you will need to **rebase your PR**.

Looking forward to hearing from you!

2021-05-19 09:31 UTC, trexfeathers requested changes
Hi @Badboy-16 ,  thanks for raising this - **we really appreciate our users becoming collaborators** 🙂. And sorry for our absence on this - we've been away on some intense project work!

Your solution looks ideal 🍻, but as mentioned in the [pull request checklist](https://scitools-iris.readthedocs.io/en/stable/developers_guide/contributing_pull_request_checklist.html) we will also need [an entry in What's New](https://scitools-iris.readthedocs.io/en/stable/developers_guide/documenting/whats_new_contributions.html#whats-new-contributions).

I also think it would be sensible to add a test confirming this is working as expected. If you'd like any help with this just shout.

Unfortunately in April we had some continuous integration issues, which we have since fixed - to bring in these fixes you will need to **rebase your PR**.

Looking forward to hearing from you!

2021-05-27 12:56 UTC, trexfeathers requested changes
Thanks for your persistence - almost there!

In addition to the 2 comments, please could you [sign the Contributor Licence Agreement](https://scitools.org.uk/cla/v4/form) - required for all Iris' pull requests.

Many Thanks.

2021-05-27 12:56 UTC, trexfeathers commented on lib/iris/tests/test_cube.py
> +class Test_CubeList_copy(tests.IrisTest):
This belongs in [`tests/unit/cube/test_CubeList.py`](https://github.com/SciTools/iris/blob/master/lib/iris/tests/unit/cube/test_CubeList.py)

I fully acknowledge Iris' testing structure is unclear!

2021-05-27 12:56 UTC, trexfeathers commented on docs/src/whatsnew/latest.rst
> +#. `@Badboy-16`_ implemented a ``CubeList.copy()`` method to return a
This link also needs creating toward the bottom of the file - [currently L172-174](https://github.com/SciTools/iris/blame/956df9912a1bec53feecec0504a0383f0dab7ea5/docs/src/whatsnew/latest.rst#L172-L174).

That will fix the test failures.

2021-05-27 14:13 UTC, Badboy-16 commented
Hi @trexfeathers 
Thanks for your comments! I have signed the agreement and pushed some commits regarding the requested changes. :)

2021-05-27 15:55 UTC, trexfeathers approved these changes

2021-05-27 15:55 UTC, merged