Update hashes for gallery wind plot
SciTools/iris pull request #4112
Opened 2021-04-30 17:22 UTC by rcomer

## 🚀 Pull Request

### Description

Closes #4110 

Image update at https://github.com/SciTools/test-iris-imagehash/pull/42

If I've understood, we don't usually remove the old hashes.  However in this case the old ones didn't include the lake outline that should have been there so were giving us false passes.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2021-04-30 17:31 UTC, trexfeathers commented
>If I've understood, we don't usually remove the old hashes.

It think it's a backwards compatibility thing. When we were putting a minimum pin on a dependency last year (#3762) I took the extra step of removing the old references (**but not the files themselves from test-iris-imagehash**), [although it was clear I wasn't expected to](https://github.com/SciTools/iris/pull/3762#issuecomment-685902750).

2021-04-30 17:35 UTC, trexfeathers requested changes
~~Following from https://github.com/SciTools/iris/pull/4112#issuecomment-830248442, please could you keep the old references too?~~

~~As I understand it, the changes are caused by new dependency versions (correct me if wrong), but we have no contract in place stating that Iris won't work with the previous dependencies, so the test harness shouldn't make this assumption either.~~

Apologies, I'd missed your point about false passing - this should **never** have been OK.

2021-04-30 18:21 UTC, trexfeathers commented
>So this is only going to pass when combined with #4108.

I'd therefore vote for 566f187fcfd40495f200020b3c7d8f1905fce67f being pushed to [jamesp:ci-lock](https://github.com/jamesp/iris/tree/ci-lock), but I expect Git decorum says we should asked @jamesp's permission first!

2021-05-04 10:32 UTC, rcomer commented
Change now incorporated into #4108, so closing this as duplicate.

2021-05-04 14:06 UTC, rcomer commented
No longer included in #4108.

2021-05-04 14:22 UTC, trexfeathers commented
@rcomer are you OK to rebase?

2021-05-04 14:52 UTC, trexfeathers approved these changes
Does as intended, one step closer to eliminating the suite of failures recently arisen on `master`. Thanks @rcomer!

2021-05-04 14:52 UTC, merged