Update cf_units pin
SciTools/iris pull request #4207
Opened 2021-06-23 15:28 UTC by lbdreyer

Related to [this change](https://github.com/conda-forge/iris-feedstock/pull/67) to the iris conda-forge recipe.

I have updated the pin for cf_units. Note there is no change to setup.cfg as that only exists on the main branch.

I had considered waiting for the mergeback then doing it on main, but as we are now planning a 3.0.3 release it makes sense to just put it here

2021-06-23 16:40 UTC, bjlittle commented
@lbdreyer We might hang fire on this PR, and wait for the latest release of `cf-units`, which means that the minimum pin is on `cftime>=1.5`

See https://github.com/SciTools/nc-time-axis/issues/71

2021-06-23 17:12 UTC, bjlittle requested changes
@lbdreyer We need to wait to make the minimum pin `cftime>=1.5`

2021-07-02 13:18 UTC, closed without merging

2021-07-02 13:18 UTC, bjlittle commented
Replaced by #4222

2021-07-02 13:18 UTC, lbdreyer commented
Closed, superceded by #4222