Add release docs sections describing the role of a Release Manager
SciTools/iris pull request #4413
Opened 2021-11-11 16:53 UTC by lbdreyer

## 🚀 Pull Request

### Description
@tkknight, earlier we discussed adding a short section to the releases docs to outline what the release manager does. What do you think of this?

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2021-11-15 12:12 UTC, tkknight requested changes

2021-11-15 12:12 UTC, tkknight commented on docs/src/developers_guide/release.rst
> +
I would suggest also linking thru to the discussion categories https://www-avd/~itkt/iris-docs-dev/src/_build/html/developers_guide/release.html stating this is where the release manager will document intent and capture any discussion points about a release.

Perhaps also update the Iris 3.2 and 3.3 discussions first post to link to this release guidance for reference.

2021-11-15 12:12 UTC, tkknight commented on docs/src/developers_guide/release.rst
> +.. _release-manager:
This is just a preference, but I suggest using underscores and not hypens, I think most other doc bookmarks use underscores too.

2021-11-16 18:06 UTC, lbdreyer commented
Thanks for the review @tkknight . I have now hopefully addressed your review comments

2021-11-17 09:08 UTC, tkknight requested changes

2021-11-17 09:08 UTC, tkknight commented on docs/src/developers_guide/release.rst
> +.. _GitHub Discussions forum: https://github.com/SciTools/iris/discussions
Suggest we could link directly to the release category https://github.com/SciTools/iris/discussions/categories/releases using the text **GitHub Releases Discussion Forum**

2021-11-17 10:13 UTC, tkknight approved these changes

2021-11-17 12:55 UTC, tkknight commented on docs/src/developers_guide/release.rst
> +.. _GitHub Discussions forum: https://github.com/SciTools/iris/discussions/categories/releases
```suggestion
.. _GitHub Releases Discussion Forum: https://github.com/SciTools/iris/discussions/categories/releases
```

2021-11-17 14:59 UTC, lbdreyer commented on docs/src/developers_guide/release.rst
> +.. _GitHub Discussions forum: https://github.com/SciTools/iris/discussions/categories/releases
Thanks @tkknight  !

2021-11-17 15:22 UTC, tkknight commented
The linkcheck has failed due to http://www.ecmwf.int/ being unreachable, the website looks to be up again just this minute.  I have rerun the cirrus task that failed, lets see what happens.  If it fails again I suggest retrying the CI tomorrow.  If the website persists as being offline we can add it to the exclude list https://github.com/SciTools/iris/blob/main/docs/src/conf.py#L303

2021-11-18 09:00 UTC, merged