Removed addition of period from wrap_lons
SciTools/iris pull request #4421
Opened 2021-11-16 18:51 UTC by akuhnregnier

Updated affected tests using assertArrayAllClose following #3993.

## 🚀 Pull Request

### Description
Please see #3994.

2021-11-16 18:55 UTC, akuhnregnier commented
Assuming the tests run for this PR, do let me know if you want me to edit the `latest.rst` file again to reflect the updated pull request (or remove it entirely from this PR).

2021-11-17 11:04 UTC, wjbenfold requested changes
Still looks good, just like the identical PR did. Having checked the values that came out of this fix, it actually improved the precision of the test result. The tests are now doing a more sane check on the floating point values.
Do please update `latest.rst` to name the right PR, just to avoid confusing anyone

2021-11-18 09:15 UTC, wjbenfold approved these changes
Looks good to me. Something slightly odd where it thinks line 120 of the whatsnew has just appeared, but that's probably from force pushing rather than pushing in some way. Will just check that as it gets merged.

2021-11-18 10:26 UTC, trexfeathers approved these changes

2021-11-18 10:26 UTC, merged