Deprecate abf and dot
SciTools/iris pull request #4515
Opened 2022-01-20 16:49 UTC by wjbenfold

## 🚀 Pull Request

### Description

See #4394 

To do:
- [ ] Work out whether this is the right way to deprecate a module - the warning for abf at least currently shows up on import of fileformats, which we may want to avoid. Not sure where to put it instead though - in every function?
- [ ] Check wording of message and consider mentioning future mitigations (undo deprecation, use plugin architecture?)

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2022-01-21 10:28 UTC, pp-mo requested changes
Looking good, but I agree we need to avoid the message when "just" importing iris.fileformats.
As with the other deprecations, I'd also like to be sure @lbdreyer had a chance to OK this.

That warning on any use of iris.fileformats happens because Iris imports abf that to populate its file format handler structures.

I think it still makes sense to issue the warning whenever abf is imported, so I think the 
nice way is to use a deferred import within a wrapper function.
I think I will propose something similar as a PR to your branch...

2022-01-21 10:45 UTC, pp-mo commented
> I think I will propose something

See https://github.com/wjbenfold/iris/pull/2

2022-01-21 15:30 UTC, wjbenfold commented
> > I think I will propose something
> 
> See [wjbenfold#2](https://github.com/wjbenfold/iris/pull/2)

I love the elegance of this solution

2022-01-24 11:52 UTC, lbdreyer commented
>As with the other deprecations, I'd also like to be sure @lbdreyer had a chance to OK this.

I'm fine with this. If we are happy to reverse the decision (or perhaps come up with an alternative!) should someone say they are still using it then that is fine.

2022-01-25 10:54 UTC, pp-mo commented
hi @wjbenfold 
something weird has happened here -- although you merged my suggestion [wjbenfold#2 ](https://github.com/wjbenfold/iris/pull/2) there is no change included here to `iris.fileformats.__init__.py`
So I think something was wrong with the merge operation + you need to address it to we have what we need here

2022-01-25 11:03 UTC, wjbenfold commented
Ah, didn't pull before the rebase, will do that

2022-01-25 13:09 UTC, wjbenfold commented
I believe that this is ready now @pp-mo

2022-01-25 14:13 UTC, pp-mo approved these changes
Ok now!

2022-01-25 14:14 UTC, merged