Overnight benchmarks
SciTools/iris pull request #4583
Opened 2022-02-11 15:31 UTC by trexfeathers

## 🚀 Pull Request

### Description

Following team discussion we have decided to run benchmarks overnight instead of them being part of the pull request CI.
* Increasing coverage is starting to bloat CI run-time.
* Current CI accuracy problems can be overcome with more benchmark repeats, but that will also bloat CI run-time.
* It is very rare that merges to `main` get released in the same day, especially those that might affect performance, so 'overnight CI' should be adequate for catching problems.

The routine starts at 23:00 each day and benchmarks every commit since 23:00 the previous day (plus the last one before this time - for comparison). Any shifts in performance are reported in a new issue, which is assigned to the author of the 'offending' pull request; see trexfeathers/iris#28 for an example.

The overnight routine is contained in the Nox `benchmarks` session, which can also be used locally to test whether the active branch will result in performance shifts when merged.

A README has also been added to the benchmarks directory to explain the specifics of our benchmarking setup.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2022-02-16 16:48 UTC, pp-mo requested changes
All a bit intricate, but we discussed "simplifying" and do agree that we don't have any neat answers, so let's get this in and not to try to improve until we need to.

Have a quick look at my  suggestions for additional comments / context, and feel free to ignore any of it.

2022-02-16 17:05 UTC, trexfeathers commented on noxfile.py
> +        asv_command_type = first_arg
b1fd50560a9eded3438aca4dce266bd6acc19dd2

2022-02-16 17:06 UTC, trexfeathers commented on noxfile.py
> +        asv_command_type = first_arg
6a4fcf94fb2da70dbbb2d82c0afbf816ff26d062

2022-02-16 23:14 UTC, pp-mo approved these changes

2022-02-16 23:14 UTC, merged

2022-02-16 23:16 UTC, pp-mo commented
It's a well thought-out solution, and in the end I could find nothing important to fix.
But it took me rather a long time to get comfortable with this, as I had a lot to learn on the way.
Thanks for your patience @trexfeathers !

2022-02-17 09:55 UTC, trexfeathers commented
Thanks @pp-mo! 🎉