Cell comparison: remove ancient netcdftime/cftime workarounds
SciTools/iris pull request #4729
Opened 2022-05-05 08:56 UTC by rcomer

## 🚀 Pull Request

### Description

Closes #4697.  The example given there now produces

```
[Cell(point=cftime.datetime(2022, 3, 8, 12, 0, 0, 0, calendar='standard', has_year_zero=False), bound=None), Cell(point=cftime.datetime(2022, 3, 9, 12, 0, 0, 0, calendar='standard', has_year_zero=False), bound=None)]
```

The first workaround was added at #1016.  From the comments on the tests I removed, the comparisons were then falling back to comparing object ids, so presumably rich comparison was not implemented in that version of netcdftime _at all_.  It is implemented now:
https://github.com/Unidata/cftime/blob/dc75368cd02bbcd1352dbecfef10404a58683f94/src/cftime/_cftime.pyx#L1314

The second workaround was added at #2440.  The comment there says that `NotImplemented` was not always being returned by the comparison method.  If I've understood correctly, @bjlittle put in a fix for this at https://github.com/Unidata/cftime/pull/81 where, as far as I can tell, python2 was the main complication.  @bjlittle's fix was merged in 2018 and we are now [pinned to cftime >= 1.5](https://github.com/SciTools/iris/blob/7db0bdb6acad80537ac33d3b051155dabfeb5e39/requirements/ci/py38.yml#L15) which is [only a year old](https://github.com/Unidata/cftime/releases/tag/v1.5.0rel).  So I think we should be safe.

I'm currently targetting `main`, but I wonder if this should actually go in a patch release?  #4697 suggests that this has now become a problem because time cell points have changed from being `datetime.datetime` to `cftime.datetime`.  This was a [breaking change in cf-units v3.0](https://github.com/SciTools/cf-units/releases/tag/v3.0.0).

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2022-05-05 09:07 UTC, rcomer commented on lib/iris/tests/unit/coords/test_Cell.py
> +        cell = Cell(cftime.datetime(2000, 1, 1))
Changed this to `cftime.datetime` as I assume the usual way for a `datetime` object to appear in a cell is via `num2date`.  E.g.
https://github.com/SciTools/iris/blob/7db0bdb6acad80537ac33d3b051155dabfeb5e39/lib/iris/coords.py#L2180-L2183

2022-05-05 10:29 UTC, trexfeathers commented
@pdearnshaw we're not planning a bugfix release for this, so it would instead be released as part of [Iris `v3.3`](https://github.com/SciTools/iris/discussions/4300). Is that OK with you or is this a particularly urgent issue?

2022-10-07 10:26 UTC, trexfeathers requested changes
@rcomer What's New and I'll merge 👍

2022-10-07 10:50 UTC, trexfeathers approved these changes

2022-10-07 10:51 UTC, merged

2022-10-07 10:51 UTC, rcomer commented
Thanks @trexfeathers!