Speed up Cube.subset/Coord.intersect
SciTools/iris pull request #4955
Opened 2022-09-09 15:38 UTC by bouweandela

## 🚀 Pull Request

### Description

This speeds up `Cube.subset` / `Coord.intersect` by using a `dict` lookup instead of `list.index` to find the indices of the coordinate that should be used for subsetting the cube.

Here is some benchmark code:

```python
import iris.cube
import iris.coords
import numpy as np

lon = iris.coords.DimCoord(np.arange(0, 360, 0.5, dtype=np.float64))
cube = iris.cube.Cube(np.arange(720, dtype=np.float32))
cube.add_dim_coord(lon, 0)
sublon = lon[(lon.points > 60) & (lon.points < 300)]

%timeit cube.subset(sublon)
```

The current `main` branch result is:
```
93.9 ms ± 4.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
and the result of running that code with this branch is:
```
13.5 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2022-09-09 18:11 UTC, bouweandela commented on lib/iris/coords.py
> +        return hash((self.point, *sorted(self.bound)))
I'm not too sure about the `sorted` here: I tried to mimic what the equals operator does, but sorting may only work if bounds is just two points.

2022-09-23 10:37 UTC, bouweandela commented on lib/iris/coords.py
> +        return hash((self.point, *sorted(self.bound)))
I got rid of the sorted, I think it should work now.

2022-10-10 13:05 UTC, lbdreyer requested changes
This is looking great, thanks @bouweandela ! Do you mind adding a [whatsnew](https://github.com/SciTools/iris/blob/main/docs/src/whatsnew/latest.rst) entry to cover this change?

2022-10-11 09:27 UTC, bouweandela commented
Thanks for the review @rcomer! I added the entry.

2022-10-11 16:04 UTC, lbdreyer approved these changes
Perfect! Thanks @bouweandela !

2022-10-11 16:04 UTC, merged