Test the calls implementing Cube and Cubelist printing, and repr_html().
SciTools/iris pull request #4976
Opened 2022-09-21 16:39 UTC by pp-mo

## 🚀 Pull Request

To address #4973 

**NOTE:** aiming this at a bugfix release, so it is derived from, and targetting '3.3.x' branch.

2022-09-21 16:40 UTC, pp-mo commented
Pure tests to start with -- proving that the Cubelist._repr_html_ test **_will fail_**.

2022-09-21 16:48 UTC, pp-mo commented
... and that should fix it.

2022-09-21 17:11 UTC, pp-mo commented
Ok, naming @trexfeathers and @lbdreyer as possible reviewers.
@lbdreyer simply because I'm still easing into Pytest usage.

We need to consider the implications for this going in a 3.3.1 release.
**TODO**: (for me) work out what a whatsnew "latest.rst" should look like in this case + initiate it.

2022-09-22 10:33 UTC, lbdreyer commented
Regarding

> TODO: (for me) work out what a whatsnew "latest.rst" should look like in this case + initiate it.

Rather than editing latest.rst. I think you just need to edit the 3.3.rst to add a section for bug fixes (as we did in https://github.com/SciTools/iris/pull/4604/files) and then add your whats new entry to this?

2022-09-22 11:21 UTC, pp-mo commented
> Regarding
> 
> > TODO: (for me) work out what a whatsnew "latest.rst" should look like in this case + initiate it.
> 
> Rather than editing latest.rst. I think you just need to edit the 3.3.rst to add a section for bug fixes (as we did in https://github.com/SciTools/iris/pull/4604/files) and then add your whats new entry to this?

Ok thanks, that makes sense !
I tried to consult the developer docs, but it isn't really clear about this IMHO

2022-09-22 11:26 UTC, lbdreyer requested changes
Tests look great! Just a few small comments

2022-09-22 11:45 UTC, pp-mo commented on lib/iris/tests/unit/cube/test_Cube.py
> +        # If a simplecube has two _DimensionalMetadata objects with the same name, the
👍 Rename+replace gone too far !

2022-09-22 11:45 UTC, pp-mo commented on lib/iris/tests/unit/cube/test_Cube.py
> +    fresh :class:`iris._representation.cube_printout.CubePrinter` object, and using it
:+1: !

2022-09-22 11:46 UTC, pp-mo commented on lib/iris/tests/unit/cube/test_CubeList.py
> +            repr_html=mock.MagicMock()  # return_value='')  # NB this must return a string
:+1: good spot !
Copied from the 'cube' case, where it did matter -- will fix.

2022-09-22 13:14 UTC, pp-mo commented
Thanks @lbdreyer 
Hope I have fixed those things now.

N.B. I am just about to check actual notebook output, but I tidied my conda + it is taking ages to build a test env ...
Best to wait for that.

2022-09-23 10:33 UTC, pp-mo commented
Ok I think this will work now : 
Fixed the glitch in the whatsnew.
I also checked that it does work as expected in a notebook :heavy_check_mark:

2022-09-23 12:17 UTC, lbdreyer commented on docs/src/whatsnew/3.3.rst
> +.. dropdown:: :opticon:`alert` v3.X.X Patches
```suggestion
.. dropdown:: :opticon:`alert` v3.3.1 Patches
```

This will also need updating

2022-09-23 14:17 UTC, lbdreyer approved these changes

2022-09-23 14:17 UTC, merged

2022-09-23 14:34 UTC, lbdreyer commented
Whoops, Looks like there was a problem with the docs build from this merge: https://readthedocs.org/projects/scitools-iris/builds/18152663/

2022-09-26 08:07 UTC, pp-mo commented
> Whoops, Looks like there was a problem with the docs build from this merge: https://readthedocs.org/projects/scitools-iris/builds/18152663/

Some kind of HDF error, could be a bit of a random glitch ?
Just trying a re-build : https://readthedocs.org/projects/scitools-iris/builds/18168111/

2022-09-26 08:31 UTC, pp-mo commented
Ok it has built, but my new whatsnew is not properly contained in the dropdown section
Need more indent.
However, I think we should shortly be adding to this section in #4933, so I will fix it there ...