Cube metadata refactortests
SciTools/iris pull request #4993
Opened 2022-09-26 17:12 UTC by pp-mo

A preliminary to addressing #4982 
I discovered that the CubeMetadata testing really needed a refactor, before I could attempt adding a 'global_attributes' field.
So this is that.

Using Pytest parametrization allows fewer tests and (a bit) less boilerplate, which also testing **_all_** the fields (which was not the case before).

The attributes behaviour still uses extra tests, but I think that is quite reasonable.  
In future, I hope to further parametrize the attribute tests, to cover both `global_attributes` and ("local")`attributes`

**WIP BECAUSE**
  - [ ] builds on #4960, so waiting for that + may need rebase

2022-09-28 13:03 UTC, pp-mo commented
NOTE: rebased from #4981 branch onto "bare" existing feature-branch

Since the changes are entirely independent, and this may well go in first, now.

2022-10-04 08:27 UTC, lbdreyer requested changes
The reduction in boilerplate is a big improvement and makes it much nicer to see what's going on with the tests!
I noticed there don't appear to be any tests for Test_difference.test_op_different_value but there are testing for that in Test__eq__ and Test_combine. Is there a reason for this?

2022-10-25 13:57 UTC, pp-mo commented on lib/iris/tests/unit/common/metadata/test_CubeMetadata.py
> +        # Check when one set of attributes has an extra entry.
:+1:

2022-10-25 13:58 UTC, pp-mo commented on lib/iris/tests/unit/common/metadata/test_CubeMetadata.py
> +        if fieldname in ("attributes",):  # 'units'):
:+1:

2022-10-25 14:22 UTC, pp-mo commented
Thanks @lbdreyer I hope this addresses your points -- please re-review !
I have added a `Test_difference.test_op_different_value` as you suggest. Also rationalised the comment descriptions of similar testcases.

2022-10-27 16:27 UTC, lbdreyer approved these changes
LGTM!

2022-10-27 16:28 UTC, merged