More tolerance NetCDF4 loading - skip un-addable dimensional metadata
SciTools/iris pull request #5054
Opened 2022-11-08 18:34 UTC by trexfeathers

## 🚀 Pull Request

### Description

Closes #3644 (and possibly some others?).

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2022-11-09 11:55 UTC, trexfeathers commented
I considered similar catching for the creation of the dimensional metadata instances during NetCDF load, but working out which of the many errors would be sensible to catch would dramatically increase scope. The 16 errors during the addition step were much easier to 'audit'.

2022-11-14 17:26 UTC, stephenworsley requested changes
Looks good, that's some gnarly monkeypatch/mock testing but I think it covers things nicely at the unit level.

I think the main thingto add here is an integration test which demonstrates the behaviour of loading a file with these invalid coordinates. This is not entirely obvious from the loading code which is quite complex, though experiments show that these variables tend to be ignored completely rather than become their own cubes. This is in a way preferable to the current behaviour where nothing would be loaded, though it's worth considering future improvements to this behaviour which retain this information in some form. I think such improvements would be quite complicated though, so we can consider this out of scope for the time being (though it would be worth adding in a comment in the integration test stating that the behaviour tested for could be revised in future).

2022-11-16 11:36 UTC, stephenworsley requested changes
Just a couple extra details to look at.

2022-11-16 14:51 UTC, trexfeathers commented on lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_dimension_coordinate.py
> +        self.monkeypatch.setattr(
c1a84f5205667b620afb342d35343f81eb5212ea

2022-11-16 14:51 UTC, trexfeathers commented on lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_dimension_coordinate.py
> +        self.monkeypatch.setattr(
c1a84f5205667b620afb342d35343f81eb5212ea

2022-11-16 14:51 UTC, trexfeathers commented on lib/iris/tests/unit/fileformats/nc_load_rules/helpers/test_build_auxiliary_coordinate.py
> +        self.monkeypatch.setattr(
c1a84f5205667b620afb342d35343f81eb5212ea

2022-11-16 14:53 UTC, trexfeathers commented on docs/src/whatsnew/latest.rst
> +   :class:`~iris.cube.Cube` (e.g. due to CF non-compliance). (:pull:`5054`)
e3a28969c592c83b8b1a92c7e6ec864eef075bd8

Good idea. But I'm pleased to say this change in error class avoids being a breaking change, as `CannotAddError` subclasses the original `ValueError`.

2022-11-16 15:17 UTC, stephenworsley approved these changes
Looks good!

2022-11-16 15:17 UTC, merged