Add trajectory interpolate tests for checking mask and dtype
SciTools/iris pull request #5062
Opened 2022-11-11 17:00 UTC by lbdreyer

## 🚀 Pull Request

### Description

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2022-11-14 12:59 UTC, trexfeathers requested changes
Thanks @lbdreyer, this must have taken a lot of sleuthing! I agree with your assessment. Also note that a similar change was made to the `linear` method this year in #4366.

Two points:

- This deserves a What's New entry
- My below question about use of fixtures

2022-11-16 16:48 UTC, lbdreyer commented on lib/iris/tests/unit/analysis/trajectory/test_interpolate.py
> +        return point(single_point_ix, single_point_iy, sample_point)
I have used a namedtuple here as this fixture returns multiple values but I want to avoid the boiler plate of having to unpack a tuple each time

2022-11-16 16:53 UTC, lbdreyer commented
Thanks for reviewing @trexfeathers ! I believe I have now addressed your comments

2022-11-16 16:58 UTC, trexfeathers approved these changes

2022-11-16 16:58 UTC, merged