Handle derived coordinates correctly in `concatenate`
SciTools/iris pull request #5096
Opened 2022-12-06 16:46 UTC by schlunma

## 🚀 Pull Request

### Description

This fixes the issue that the result of `iris.cube.CubeList.concatenate` loses any derived coordinate present in the input cubes. Here, this is fixed for all derived coordinates (for those that span the concatenated dimensions and for those that don't).

### Todo

- [ ] Add tests
- [ ] Redo the same for `merge` if easily possible

Closes #2478 

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2023-03-31 12:49 UTC, schlunma commented
Hi, any chance this can make it into 3.5? That would be awesome!! Anything I can do to support you?

2023-04-05 13:05 UTC, ESadek-MO commented
> Hi, any chance this can make it into 3.5? That would be awesome!! Anything I can do to support you?

Hey, I'll be looking into this soon God willing, sorry for the delay! Should be able to make it in, fingers crossed!

2023-04-09 13:02 UTC, ESadek-MO requested changes
Hey @schlunma. Thanks for this, looks good to me!

Would you be able to add a What's New entry just briefly explaining what you've done? Then should be good to go!

2023-04-11 09:25 UTC, schlunma commented
I will adapt the tests so coverage in changed lines will be 100%

2023-04-12 08:28 UTC, ESadek-MO approved these changes

2023-04-12 08:28 UTC, merged