Fixing typo's in Gitwash.
SciTools/iris pull request #5145
Opened 2023-02-01 14:47 UTC by HGWright

## 🚀 Pull Request

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2023-02-02 14:37 UTC, bjlittle requested changes
Welcome aboard @HGWright :partying_face: 

This PR looks good to me. Thanks for your first (of many :wink:) contribution to `iris`!

I think that it's totally appropriate for you to add an entry to the `whatsnew` [latest.rst](https://github.com/SciTools/iris/blob/main/docs/src/whatsnew/latest.rst). In particular,

- to the [Announcements](https://github.com/SciTools/iris/blob/main/docs/src/whatsnew/latest.rst#-announcements) section, highlighting that this is your **first** contribution (see the first entry [here](https://scitools-iris.readthedocs.io/en/v3.4.0/whatsnew/index.html#announcements) in the `iris` v3.4.0 release `whatsnew`, as an example)
- to the [Documentation](https://github.com/SciTools/iris/blob/main/docs/src/whatsnew/latest.rst#-documentation) section, detailing your change. Simply follow the style guide and format of other existing entries 

Lookin' forward to banking this PR :smile:

2023-02-02 15:51 UTC, bjlittle commented on docs/src/developers_guide/gitwash/set_up_fork.rst
> -   git remote add upstream git://github.com/SciTools/iris.git
Nice spot :eagle: :eyes:

2023-02-03 15:43 UTC, bjlittle commented
@HGWright As you aren't an `iris` core developer yet, you need to add and entry at the bottom of the `latest.rst` to resolve the link to our GH user i.e.,
```
.. comment
    Whatsnew author names (@github name) in alphabetical order. Note that,
    core dev names are automatically included by the common_links.inc:

.. _@HGWright: https://github.com/HGWright                     <------ add this here
```
If you don't do this, then you'll find that your user name is a broken link. Confirm this is the case by building the docs and viewing the `latest.rst` before and after you make this change.

2023-02-03 15:46 UTC, bjlittle commented on docs/src/whatsnew/latest.rst
> +
Minor point, but we have **two** blank lines between sections to help the developers eye when writing the docs

2023-02-03 15:47 UTC, trexfeathers commented
> @HGWright As you aren't an `iris` core developer yet, you need to add and entry at the bottom of the `latest.rst` to resolve the link to our GH user i.e.,
> 
> ```
> .. comment
>     Whatsnew author names (@github name) in alphabetical order. Note that,
>     core dev names are automatically included by the common_links.inc:
> 
> .. _@HGWright: https://github.com/HGWright                     <------ add this here
> ```
> 
> If you don't do this, then you'll find that your user name is a broken link. Confirm this is the case by building the docs and viewing the `latest.rst` before and after you make this change.

That's my bad @bjlittle! @HGWright asked me and I encouraged him to put the link into `common_links.inc`. I think we put @ESadek-MO there before he was a core dev, too. Do you reckon this method is a problem?

2023-02-03 16:36 UTC, bjlittle commented
> That's my bad @bjlittle! @HGWright asked me and I encouraged him to put the link into `common_links.inc`. I think we put @ESadek-MO there before he was a core dev, too. Do you reckon this method is a problem?

No worries, all good. Yup, my eye glazed over that entry. I'm happy if you are. All good :smile:

2023-02-03 16:39 UTC, bjlittle approved these changes

2023-02-03 16:39 UTC, merged