Add histogram convenience for passing Iris objects to plt.hist
SciTools/iris pull request #5189
Opened 2023-03-09 11:57 UTC by lbdreyer

Closes #3330 

This adds a simple convenience function for creating histograms with Iris objects.
`iris.plot.hist` and `iris.quickplot.hist` takes Iris objects (cube, coords, cell measures and ancil vars) extract the values from the objects and passes it onto `plt.hist`

Note most of our plotting stuff only handles cubes/coords, but I have included other dimensional metadata objects.

This PR requires the graphics tests results to be merged in: https://github.com/SciTools/iris-test-data/pull/84

2023-03-09 12:37 UTC, rcomer commented on lib/iris/quickplot.py
> +    axes.set_ylabel("Frequency")
I agree auto-labelling is consistent with other quickplot functions, but the correct label might depend on keywords such as `density` and `cumulative`.

2023-03-09 12:43 UTC, rcomer commented on lib/iris/quickplot.py
> +    axes.set_ylabel("Frequency")
There is also an `orientation` keyword which flips x and y…

2023-03-09 13:38 UTC, trexfeathers commented
BTW @rcomer if you feel this is in scope for your work and you have time then we're a little short on reviewers this week... 🥰

But I understand if not.

2023-03-09 15:55 UTC, lbdreyer commented on lib/iris/quickplot.py
> +    axes.set_ylabel("Frequency")
Thanks for pointing that out @rcomer ! I have now removed the "Frequency" label, and just set the x/ylabel depending on the orientation

2023-03-10 17:48 UTC, trexfeathers requested changes
Great! Thanks @lbdreyer this is a neat addition to make users' lives easier.

A couple of iris-test-data references need changing to `2.19`:

https://github.com/SciTools/iris/blob/e2dc89cb0df6b00a03c582a02b4e187b5a93bba3/.github/workflows/ci-tests.yml#L52-L54

https://github.com/SciTools/iris/blob/e2dc89cb0df6b00a03c582a02b4e187b5a93bba3/.github/workflows/benchmark.yml#L21-L28

2023-03-13 16:31 UTC, lbdreyer commented on lib/iris/plot.py
> +    :class:`~iris.coords.CellMeasure`, or :class:`~iris.coords.AncillaryVariable`
It didn't all fit on the one line so I've just moved it to the line below

2023-03-13 16:31 UTC, lbdreyer commented
Thanks for the review @trexfeathers !
I believe I have now actioned your comments

2023-03-17 15:05 UTC, trexfeathers approved these changes

2023-03-17 15:05 UTC, merged

2023-03-23 10:34 UTC, BenMGeo commented
Thank you for adding this. :heart: