Adopt sphinx-apidoc and retire complex sphinxext
SciTools/iris pull request #5264
Opened 2023-04-20 15:31 UTC by tkknight

## 🚀 Pull Request

### Description
Retire the old and convoluted sphinx extensions to generate the Iris API documentation.

- Uses [sphinx-apidoc](https://github.com/sphinx-contrib/apidoc) instead
- The indented blank line is now gone that appeared at the top of some API doc pages
- The "**In this module:**" section  is now not present (part of the old extensions), this is fine as the right hand sidebar shows this now.
- At the bottom of each page the TOC (Table of contents) for all child packages or modules is displayed.  I think this is useful, especially if viewing on a smaller screen where the sidebar may be hidden.
- The order or sidebar contents are different but all are present
- The docstrings can be in a slightly different place but all are present I believe (I welcome someone doing a review to check some api doc pages)
- There is still a sphinxext (new one) that will remove the word **package** and **module** that make the sidebar hard to read imho.  I cannot find any option in **sphinx-apidoc** itself to disable this.
   - Without **package** and **module** in the sidebar (and headings)
      - ![image](https://user-images.githubusercontent.com/2108488/233414095-61d030fa-dc00-4d6c-a782-8f5c76f577d8.png)
  - With **package** and **module** in the sidebar (and headings)
     - **package** and **module** in the sidebar (and headings)
       - ![image](https://user-images.githubusercontent.com/2108488/233412624-81e672ae-cc99-443d-a2d1-560c5f9c706f.png)

There are many incorrect indentations and incorrect syntax in the docstrings that should be using the [numpydocs](https://scitools-iris.readthedocs.io/en/latest/developers_guide/documenting/docstrings.html#docstrings), I may address those in a separate PR.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2023-04-20 15:32 UTC, trexfeathers commented
OMG ❤

2023-04-20 18:33 UTC, rcomer commented
😍

Think the linkcheck failure is https://github.com/matplotlib/matplotlib/issues/25731

2023-04-20 22:15 UTC, bjlittle commented
> heart_eyes
> 
> Think the linkcheck failure is [matplotlib/matplotlib#25731](https://github.com/matplotlib/matplotlib/issues/25731)

There been a server outage for the `mpl` docs most of the afternoon, but it's back up now.

I respun the CI and all is well now :smile:

2023-04-24 09:12 UTC, pp-mo approved these changes
Don't usually comment on docs PRs, but this one is a great improvement !
🚀

2023-04-24 09:12 UTC, pp-mo commented on docs/src/whatsnew/latest.rst
> +#. `@tkknight`_ removed the legacy custom sphinx extensions that generates the
```suggestion
#. `@tkknight`_ removed the legacy custom sphinx extensions that generate the
```
tiny typo

2023-04-25 10:39 UTC, bjlittle requested changes
@tkknight This is fantastic! 🥇 

I've been waiting for us to purge the custom extensions for many years... that said, they've served their purpose very well indeed.

Since #5274 landed, which also changed the lock files, could you rebase your PR and re-generate the lock files with your new `sphinxcontrib-apidoc` dependency 👍

2023-04-25 11:36 UTC, merged

2023-04-27 13:34 UTC, pp-mo commented on requirements/locks/py39-linux-64.lock
> +https://conda.anaconda.org/conda-forge/linux-64/numpy-1.23.5-py39h3d75532_0.conda#ea5d332e361eb72c2593cf79559bc0ec
note: same in all 3 lockfiles ?