Dark theme ready
SciTools/iris pull request #5299
Opened 2023-05-02 14:18 UTC by tkknight

## 🚀 Pull Request

### Description
Updates the Iris docs to be dark theme ready.  This is a feature that the [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html) supports.

#### TODO

- [ ] Wait until Iris 3.6 is released
- [ ] Add whatsnew

#### Changes include

- Enabled the dark theme, this now adds an icons that toggles auto/dark/light (top right corner ish)
- ``svg`` images have an increased border to so when there is a dark background it looks better
- All images are transparent where appropriate
- datatables (used for the issue voting table)
   - Updated the datatables version (no visible changes here but I may have made the table dark mode friendly as it was not before hand)
   - Added some useful defaults for the table presentation
- Updated the dropdown syntax when using the code icon
- Specific a `dark-light` class where the figure/image is transparent, otherwise the theme will add a white background to the transparent image when using dark more.  Sometimes this is ok though so the class has not been used everywhere.

#### Minor issue outstanding

The Iris Voted Issue table **(ADD LINK)** looks ok apart from the pulldown and text entry that uses black text on the almost black background, making it very hard to read.  This is not a major issue and unless there are objections should not stop this PR.

I expect this issue will resolve itself when `pydata-sphinx-theme` is updated (and we unpin it) or when the `datatables `css is updated.

![image](https://user-images.githubusercontent.com/2108488/235692891-9cf7515c-bf69-49f2-9c67-56a5d3cacb7f.png)

![image](https://user-images.githubusercontent.com/2108488/235693016-d033fa35-8d52-4e4a-9dab-93cbfec57a40.png)

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2023-05-23 09:26 UTC, tkknight commented
Ready for review.

2023-05-23 16:53 UTC, trexfeathers requested changes
Thanks @tkknight. At least one fix to an image is needed, plus a few other comments.

2023-05-23 16:53 UTC, trexfeathers commented on docs/src/voted_issues.rst
The poor rendering of the table is pretty frustrating, but I don't want to get in the way of the PR so I'll try to be less squeamish.

2023-05-23 16:53 UTC, trexfeathers commented on docs/src/_static/theme_override.css
Could you provide a reference / explanation for this change? I'm not sure where to look.

2023-05-24 10:43 UTC, tkknight commented on docs/src/userguide/merge_and_concat.svg
Fixed.

2023-05-24 10:44 UTC, tkknight commented on docs/src/voted_issues.rst
I plan to check for datatables and theme updates that may fix this in future.

2023-05-24 10:45 UTC, tkknight commented on docs/src/userguide/cube_diagram.png
deleted.

2023-05-24 10:48 UTC, tkknight commented on docs/src/_static/theme_override.css
If you view the live docs https://scitools-iris.readthedocs.io/en/latest/ and press F12, in the top right you will see a red cross with the number or html/css/script errors, mine shows 5.  The built docs https://scitools-iris.readthedocs.io/en/latest/ for this PR corrects a path so it is found correctly, now showing only 4 errors.  The remaining errors I suspect are due to the Met Office firewall.

2023-05-24 10:55 UTC, trexfeathers approved these changes

2023-05-24 10:57 UTC, trexfeathers commented
Great, thanks @tkknight! Let's save some monitor energy and some retinas 💻👁 ...

2023-05-24 10:57 UTC, merged