address concatenate lazy comparison truthiness
SciTools/iris pull request #5353
Opened 2023-06-16 08:38 UTC by bjlittle

## 🚀 Pull Request

### Description

This PR is a follow-on to #5142.

Lazy comparison will always yield a truthy value, therefore we require to realize the comparison. In this case, we're performing either lazy indexing for a single value or comparing lazy single values. Realizing the result won't undo the intent of #5142.

To do:

 - [ ] Add a test case/s to highlight the issue and ratify adoption of `as_concrete_data` pattern

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2023-06-16 09:07 UTC, bjlittle commented
Ping @sloosvel, just so you're aware :+1:

2023-06-18 23:02 UTC, bjlittle commented on lib/iris/_concatenate.py
> +            elif coord.points[-1] > coord.points[0]:
We're exclusively dealing with `DimCoord`s here. Therefore the points and bounds are **never** lazy, so there is no need to use `core_points` to access the realized data.

2023-06-18 23:04 UTC, bjlittle commented on lib/iris/_concatenate.py
> +                        _Extent(coord.bounds[-1, 1], coord.bounds[0, 1]),
Same applies here in `iris._concatenate._CoordSignature._calculate_extents`.

We're dealing exclusively with `DimCoord`s, therefore the `points` and `bounds` are **never** lazy and always realized.

2023-06-19 14:38 UTC, trexfeathers requested changes
Thanks @bjlittle, this all makes sense to me.

A few changes to improve test readability:

2023-06-19 14:38 UTC, trexfeathers commented on lib/iris/tests/unit/concatenate/test__CoordMetaData.py
> +@pytest.mark.parametrize("with_bounds", [False, True])
Hoping to have a future discussion with @ESadek-MO about the trade-off of readability vs utility when it comes to combining Parametrization and Fixtures.

2023-06-19 20:09 UTC, bjlittle commented on lib/iris/tests/unit/concatenate/__init__.py
> +        coord.metadata = coord.metadata.from_metadata(metadata)
This is subtle, but a useful pattern that's not well known or used within `iris`, so I'll add a comment to clarify.

This step is necessary. Essentially, it's an ease way to convert one metadata instance to another. At this point `coord` is an `AuxCoord` and `metadata` is a `DimCoordMetadata` instance. The `from_metadata` method is being called on the `AuxCoord`s metadata, which is an `AuxCoordMetadata` instance, and it knows what attributes it needs to cast the `DimCoordMetadata` to an `AuxCoordMetadata` i.e., drop the `circular` attribute from `DimCoordMetadata`. The resultant cast is assigned to the `coord.metadata`.

For reference, see [here](https://scitools-iris.readthedocs.io/en/latest/further_topics/metadata.html#metadata-conversion).

2023-06-20 13:32 UTC, trexfeathers commented on lib/iris/tests/unit/concatenate/__init__.py
> +        coord.metadata = coord.metadata.from_metadata(metadata)
OMG, with this knowledge I can now see that I made a real hash of a user support item a while back! We were manually adding and removing bits of metadata 😳

2023-06-20 13:32 UTC, trexfeathers commented on lib/iris/tests/unit/concatenate/__init__.py
> +        coord.metadata = coord.metadata.from_metadata(metadata)
OMG, with this knowledge I can now see that I made a real hash of a user support item a while back! We were manually adding and removing bits of metadata 😳

2023-06-20 13:33 UTC, trexfeathers approved these changes

2023-06-20 13:33 UTC, merged

2023-06-20 13:45 UTC, bjlittle commented
@trexfeathers Awesome, thanks 🍻