Self-contained runnable sample code for basic mesh plotting.
SciTools/iris pull request #5501
Opened 2023-09-15 16:17 UTC by pp-mo

Attempts to at least partially address #5500 

The new sample code I believe works, and produces the provided plot.

2023-09-15 16:22 UTC, bjlittle commented
@pp-mo Adding `import geovista.theme` gives you better default colours IMHO.

Although, if you do this here, you'd probably want to be consistent and also do this throughout all the `geovista` examples

2023-09-15 16:48 UTC, bjlittle commented on docs/src/further_topics/ugrid/operations.rst
> +        ...
@pp-mo You can now simplify the call to `Transform.from_unstructured` as follows:

```python
mesh = Transform.from_unstructured(
    lons.points,
    lats.points,
    connectivity=indices,
    data=cube.data,
    name=f"{cube.name()} / {cube.units}",
)
```

There is now no need to provide the `start_index` as `geovista` will detect this, and it's better to name the `indices` with the `connectivity` kwarg for clarity.

2023-09-15 16:49 UTC, bjlittle commented on docs/src/further_topics/ugrid/operations.rst
> +        >>> my_plotter.background_color = "#502020ff"
If you use `import geovista.theme` there's no need to set the `background_color`

2023-09-15 16:56 UTC, bjlittle commented on docs/src/further_topics/ugrid/operations.rst
> +        >>> _ = my_plotter.add_mesh(face_polydata, radius=1.0)
There's no real need here to set the `radius`, it's not adding anything of great value to "basic" plotting... it's just a distraction.

If you're concern is that the `mesh` is so low resolution that it's markedly different from the spherical coastlines, then only specify the `radius` for the coastlines. Setting the `radius=1.0` for the `face_polydata` is a nop.

2023-09-15 20:51 UTC, bjlittle requested changes
@pp-mo I've raised some questions for you to consider

2025-12-03 10:30 UTC, ESadek-MO commented
From @SciTools/peloton: This was closed by mistake, we think this is still worth doing!

2025-12-03 10:59 UTC, pp-mo commented
I revived the branch, which I deleted by mistake !

2025-12-03 12:06 UTC, pp-mo commented
Well, as @trexfeathers pointed out, we do now have [this mini geovista example](https://scitools-iris.readthedocs.io/en/v3.14.0/further_topics/ugrid/operations.html#plotting) in Iris docs.

It's not in the gallery, but maybe it doesn't need to be?
I guess people with this type of data will know that it is geovista they need.

**If that's enough, we can close this?**

2025-12-03 12:08 UTC, trexfeathers commented
> Well, as @trexfeathers pointed out, we do now have [this mini geovista example](https://scitools-iris.readthedocs.io/en/v3.14.0/further_topics/ugrid/operations.html#plotting) in Iris docs.
> 
> It's not in the gallery, but maybe it doesn't need to be? I guess people with this type of data will know that it is geovista they need.
> 
> **If that's enough, we can close this?**

I would support a full-on gallery entry, but the existing documentation means I'd be comfortable leaving this too, if we'd rather focus on other priorities.

2026-04-08 09:50 UTC, ESadek-MO commented
From @SciTools/peloton 

This has alreay been completed; we need an issue for copying this example over to the gallery!

2026-04-08 09:50 UTC, closed without merging