Refactor area weighted regridding, improve performance
SciTools/iris pull request #5543
Opened 2023-10-13 11:11 UTC by stephenworsley

## 🚀 Pull Request

### Description
Implements #5365.

2023-11-07 17:17 UTC, stephenworsley commented
Note: this PR builds a wights matrix and performs regridding with the expectation that the standard cube has the last two dimensions as the y and x dimension (see the change made in this commit https://github.com/SciTools/iris/pull/5543/commits/90130ccc054b336339efeb37458fcaeaf566aa39). This decision is made in order to maintain consistency with patterns established in existing regridders, e.g. the ordering of `dims` expected in this line for example:
https://github.com/SciTools/iris/blob/e0850ebc73824c929f48d51067f88c3c2067b7fb/lib/iris/analysis/_regrid.py#L365
This cosistency is important so that further unification of regridding can take place without having to change the expected ordering of weights matrices associated with regridders.

This decision is also in keeping with recomendations in CF conventions, see http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#dimensions

2023-11-20 12:27 UTC, HGWright requested changes
Fantastic performance benefits, great work. Just a few minor changes.

2023-11-20 12:27 UTC, HGWright commented on lib/iris/analysis/_area_weighted.py
> +        x_none = True
Can simplify this code by removing `x_none` and `y_none`, and instead just tracking the number of added scalar coords. This also effects the `np.squeeze` at the bottom of this code.

2023-11-20 12:27 UTC, HGWright commented on lib/iris/analysis/_area_weighted.py
> +    normalisations *= tgt_mask
We believe this can be simplified using something like `normalisations = tgt_mask.copy`.

2023-11-20 15:38 UTC, stephenworsley commented on lib/iris/analysis/_area_weighted.py
> +    result = result * normalisations
It turns out that the behaviour of `x *= y` is slightly different to `x = x * y`, see https://stackoverflow.com/questions/35496704/numpy-not-working

2023-11-20 16:49 UTC, HGWright commented on lib/iris/analysis/_area_weighted.py
> +    result = result * normalisations
Oh i didn't spot that difference. Good catch and therefore given the multiplication from `array` to a `masked array` the fact that *= in an inplace action that wouldn't work.

2023-11-20 16:52 UTC, HGWright approved these changes
Great work @stephenworsley, merging this and we will add a whatsnew entry in a seperate PR

2023-11-20 16:54 UTC, merged