Allowing exemption to axis guessing on coords
SciTools/iris pull request #5551
Opened 2023-10-25 12:56 UTC by HGWright

## 🚀 Pull Request

### Description

This PR adds a coordinate property `guess_coord` that forces `guess_coord_axis` to return `None`.

Tests for `guess_coord` and `guess_coord_axis` added.

Closes #5003

---

2023-10-25 13:11 UTC, trexfeathers commented on lib/iris/coords.py
> +        guess_coord=True,
This is the thing that everyone was against in our first meeting, after which we reduced the proposal to a coordinate property that could be set, but not during instantiation.

2023-10-25 13:52 UTC, trexfeathers commented on lib/iris/util.py
> +    to False.
```suggestion
    Can be skipped by setting the :class:`~iris.coords.Coord` 
    :attr:`~iris.coords.Coord.guess_coord` attribute
    to ``False``.
```

2023-11-09 13:29 UTC, bjlittle requested changes
@HGWright It's taking shape, so thanks for persevering 💯 

He's some initial suggestions 👍

2023-11-09 13:29 UTC, bjlittle commented on lib/iris/coords.py
> +            When True: guess_coord will guess the coord, when False it won't.
@HGWright This comment, no longer needed.

2023-11-09 13:29 UTC, bjlittle commented on lib/iris/coords.py
> +            emsg = "Ignore_axis can only be set to True or False"
```suggestion
            emsg = "'ignore_axis' can only be set to 'True' or 'False'."
```

2023-11-09 13:29 UTC, bjlittle commented on lib/iris/coords.py
> +            element.setAttribute("guess_coord", str(self.guess_coord))
```suggestion
        if self.ignore_axis:
            element.setAttribute("ignore_axis", str(self.ignore_axis))
```

2023-11-09 13:29 UTC, bjlittle commented on lib/iris/util.py
> +    if coord.ignore_axis is True:
```suggestion
    if hasattr(coord, "ignore_axis") and coord.ignore_axis is True:
```

2023-11-09 14:04 UTC, bjlittle commented on lib/iris/coords.py
> +            element.setAttribute("ignore_axis", str(self.ignore_axis))
```suggestion
        if hasattr(self, "ignore_axis") and self.ignore_axis:
            element.setAttribute("ignore_axis", str(self.ignore_axis))
```

2023-11-09 14:16 UTC, bjlittle commented on lib/iris/coords.py
> +            element.setAttribute("ignore_axis", str(self.ignore_axis))
Actually ... thinking on this, I don't believe that we should capture the state of `ignore_axis` within the CML. We're not interested in stateful equality here, and we've got separate unit test coverage to give us confidence that the new behaviour is working as expected.

So yeah, I vote from removing this. I genuinely don't see the benefit from the effort of extending the CML here.

@HGWright Thoughts?

2023-11-17 10:14 UTC, bjlittle requested changes
@HGWright This is looking really good.

Just a few minor actions to service, then we can bank this 👍

2023-11-17 10:14 UTC, bjlittle commented on lib/iris/tests/unit/util/test_guess_coord_axis.py
> +        assert guess_coord_axis(coord) == "T"
@HGWright You could parameterize these two tests into one ...

2023-11-17 10:14 UTC, bjlittle commented on lib/iris/tests/unit/util/test_guess_coord_axis.py
> +        assert guess_coord_axis(coord) is None
@HGWright Perhaps parameterize and explicitly test with `ignore_axis` being set to `True`  and then `False`.

2023-11-17 10:14 UTC, bjlittle commented on lib/iris/util.py
> +    to False.
```suggestion
    The ``guess_coord_axis`` behaviour can be skipped by setting the coordinate property ``ignore_axis`` to ``False``.
```

2023-11-17 10:30 UTC, bjlittle commented
@HGWright You also need to add a `whatsnew` entry 👍

2023-11-17 10:31 UTC, bjlittle commented
@HGWright Could you also raise an issue to capture the need to document these changes.

We can action that separately, rather than bloat the scope of this pull-request.

2023-11-17 16:05 UTC, bjlittle commented on docs/src/whatsnew/latest.rst
> +
?

2023-11-17 16:08 UTC, bjlittle commented on docs/src/whatsnew/latest.rst
> +   #. `@HGWright`_ added :func:`~iris.coords.Coord.ignore_axis` to allow manual
```suggestion
   #. `@HGWright`_ added :attr:`~iris.coords.Coord.ignore_axis` to allow manual
```

2023-11-17 16:09 UTC, bjlittle commented on docs/src/whatsnew/latest.rst
> +   #. `@HGWright`_ added :func:`~iris.coords.Coord.ignore_axis` to allow manual
For further details, see [here](https://www.sphinx-doc.org/en/master/usage/domains/python.html#role-py-attr).

2023-11-17 16:19 UTC, bjlittle approved these changes

2023-11-17 16:19 UTC, merged