ruff compliance for D205.
SciTools/iris pull request #5681
Opened 2024-01-08 15:25 UTC by tkknight

## 🚀 Pull Request

# **WORK IN PROGRESS - DO NOT REVIEW**

### Description
PR solely for fixing `D205: 1 blank line required between summary line and description`

Continues work of https://github.com/SciTools/iris/issues/5625.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2024-01-11 17:39 UTC, bjlittle requested changes
@tkknight Gosh. This was hard.

You've make an incredible effort to reformat the docstrings. 

I've tried my best to complement your efforts to formulate an appropriate single line summary for each docstring. We don't need perfection here, as we can iterate over time and massage the content.

A bunch of suggestions which you can accept or not.

Either way, a huge effort and a decent step forwards :100: :+1:

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/fileformats/cf.py
> +        """Determine the dimensionality of this variable is a subset.
```suggestion
        """Determine dimensionality coverage.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/fileformats/cf.py
> +        """Determine whether the dimensionality of this variable is a subset.
```suggestion
        """Determine dimensionality coverage.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/fileformats/cf.py
> +        """Determine if dimensionality is a subset of the specified target variable.
```suggestion
        """Determine dimensionality coverage.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/fileformats/_structured_array_identification.py
> +        """The ``size`` attribute is the number of the unique values in the original array.
```suggestion
        """Number of unique values in the original array.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/fileformats/_structured_array_identification.py
> +        """The inverse operation of :func:`ArrayStructure.from_array`.
```suggestion
        """Build 1D array.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """Create :class:`xml.dom.minidom.Element` that describes :class:`_DimensionalMetadata`.
```suggestion
        """Create XML element.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +    """An immutable representation of a single cell of a coordinate.
```suggestion
    """An coordinate cell containing a single point, or point and bounds.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """Common method called by the rich comparison operators.
```suggestion
        """Common equality comparison.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """The coordinate bounds values, as a NumPy array.
```suggestion
        """Coordinate bounds values.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """A boolean that controls whether the coordinate is a climatological time axis.
```suggestion
        """Flag for representing a climatological time axis.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """Return a boolean whether the coord's bounds array is a lazy dask array or not.
```suggestion
        """Whether coordinate bounds are lazy.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """Check if the Coord is bounded with contiguous bounds.
```suggestion
        """Whether coordinate has contiguous bounds.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """Return the N+1 bound values for a contiguous bounded 1D coordinate.
```suggestion
        """Contiguous bounds of 1D coordinate.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """The NumPy dtype of the coord's bounds.
```suggestion
        """The NumPy dtype of the coordinates bounds.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/coords.py
> +        """Return the single :class:`Cell` instance from slicing the points/bounds.
```suggestion
        """The point/bound cell at the given coordinate index.
```

2024-01-11 17:39 UTC, bjlittle commented on lib/iris/experimental/ugrid/mesh.py
> +    """A CF-UGRID topology connectivity, describes the topological relationship.
```suggestion
    """CF-UGRID topology.
```

2024-01-12 16:01 UTC, tkknight commented
All review comments accepted - one at a time until I reliased there was a batch option!

One additional commit from my final read thru, minor layout and spotted some duplicate text.  See https://github.com/SciTools/iris/pull/5681/commits/d168d07a660affbf696e48876e24623fd8a516e8.

Think this is now ready.

2024-01-12 23:10 UTC, bjlittle approved these changes

2024-01-12 23:10 UTC, merged