Removed use of catch_warnings
SciTools/iris pull request #5685
Opened 2024-01-09 14:37 UTC by ESadek-MO

Closes #5536.

Removed catch_warnings, by moving the functionality to parse_cell_methods()

2024-01-09 16:34 UTC, stephenworsley commented
## Before:
![image](https://github.com/SciTools/iris/assets/49274989/793d9347-cf3c-4cd9-ab9d-34533de7e0ec)

## After:
![image](https://github.com/SciTools/iris/assets/49274989/39ca6057-73c2-461d-a2f6-f11b345f0baa)

Compare with https://github.com/SciTools/iris/pull/5506#issuecomment-1729102179

2024-01-10 12:33 UTC, stephenworsley requested changes
Looks good, I think this could do with a test to explicitly check that this avoids warning repeats similar to this one (feel free to copy this test) https://github.com/SciTools/iris/pull/5506/files#diff-517f51f31e7b2402608486de8f2f1a79f004d9591eb17869451b9f27a61518b3R495

2024-01-11 16:20 UTC, stephenworsley requested changes
Looking good, just a couple thoughts about how the tests might be made more robust to future changes to warning behaviour.

2024-01-11 16:20 UTC, stephenworsley commented on lib/iris/tests/integration/netcdf/test_general.py
> +            "toa_brightness_temperature.nc",
So I've run some tests and I think this file would actually cause a warning repeat if there were files after it, for the sake of making it clear which files are expected not to cause repeats, I think this should be commented out for the time being with a comment noting that this file still causes warning repeats.

2024-01-11 16:20 UTC, stephenworsley commented on lib/iris/tests/integration/netcdf/test_general.py
> +    def test_datum_default(self):
Upon reflection, I think this test is less relevant to this PR and given that its behaviour might change in future it would be better to be removed.

2024-01-11 16:46 UTC, stephenworsley requested changes
Just a couple tweaks to the comments here

2024-01-11 16:46 UTC, stephenworsley commented on lib/iris/tests/integration/netcdf/test_general.py
> +        toa_brightness_temperature.nc has lazy data, and triggers a
To be precise, it has an AuxCoord with lazy data.

2024-01-11 16:46 UTC, stephenworsley commented on lib/iris/tests/integration/netcdf/test_general.py
> +        so has been removed from the `fnames` list.
I think it's elaborating "... a `catch_warnings()` call _which causes warnings to be repeated,_ so has been removed from the `fnames` list _until a solution is found for such a file._"

2024-01-11 16:46 UTC, stephenworsley commented on lib/iris/tests/integration/netcdf/test_general.py
> +            #
The file name should still be here, but commented out.

2024-01-11 16:56 UTC, stephenworsley commented on lib/iris/tests/integration/netcdf/test_general.py
> +        toa_brightness_temperature.nc has an AucCoord lazy data, and triggers a
*Au _x_ Coord _with_ lazy data

2024-01-11 16:59 UTC, ESadek-MO commented on lib/iris/tests/integration/netcdf/test_general.py
> +        toa_brightness_temperature.nc has an AucCoord lazy data, and triggers a
Embarrassing, my apologies

2024-01-11 17:11 UTC, stephenworsley commented on lib/iris/fileformats/_nc_load_rules/helpers.py
> +                    )
I think it might actually be worth adding a `msg = None` here to ensure this warning isn't repeated at the end of the function.

2024-01-11 17:24 UTC, stephenworsley approved these changes
Looks good!

2024-01-11 17:25 UTC, merged

2024-01-12 12:12 UTC, trexfeathers commented
Should there have been a What's New entry here?