typos
SciTools/iris pull request #5759
Opened 2024-02-20 13:29 UTC by acchamber

## 🚀 Pull Request

### Description
Fixed some typos, prettied some formatting, and cleaned up some of the wording in the userguide for shapefiles

---

2024-04-04 15:11 UTC, bjlittle requested changes
@acchamber Lovely update, thanks 💯 

Just some minor suggestions to service, then we can bank this 🍻

2024-04-04 15:11 UTC, bjlittle commented on docs/src/userguide/subsetting_a_cube.rst
> +accessible via cartopy. Users may also provide their own custom shapefiles for cartopy to load, or their own underlying geometry in the same format as a shapefile geometry.
If you agree tp make this change then please add `.. include:: ../common_links.inc` at the top of the this file.

2024-04-04 15:11 UTC, bjlittle commented on docs/src/userguide/subsetting_a_cube.rst
> +These geographical features can often be described by shapefiles, Shapefiles are a file format first developed for GIS software in the 1990s, and now `Natural Earth`_ maintain a large freely usable d
If you agree to make this change then please add there reference to the ESRI whitepaper

`.. _ESRI Shapefiles: https://support.esri.com/en-us/technical-paper/esri-shapefile-technical-description-279`

to the tail of this file.

2024-04-04 15:11 UTC, bjlittle commented on docs/src/userguide/subsetting_a_cube.rst
> +The `.geometry` attribute of the records in the reader contain the shapely polygon we're interested in. They contain the coordinates that define the polygon (or set of lines) being masked
If you agree to make this change then please add

`.. _Shapely: https://shapely.readthedocs.io/en/stable/index.html`

to the `docs/src/common_links.inc` file.

2024-04-08 16:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SciTools/iris?pullRequest=5759) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SciTools/iris?pullRequest=5759) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SciTools/iris?pullRequest=5759) it.</sub>

2024-04-12 14:29 UTC, acchamber commented
Thanks for the review Bill, made the requested changes and added the extra links.

2024-04-15 08:22 UTC, bjlittle approved these changes

2024-04-15 08:22 UTC, bjlittle commented
Awesome, thanks @acchamber 🍻

2024-04-15 08:22 UTC, merged