DOCS: Enable numpydoc validation pre-commit hook
SciTools/iris pull request #5762
Opened 2024-02-20 16:43 UTC by tkknight

## 🚀 Pull Request

### Description

This pull-request enables the `numpydoc` pre-commit hook, which performs [validation checks](https://numpydoc.readthedocs.io/en/latest/validation.html) of all python docstrings to ensure that they comply with the [numpydoc validation rules](https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks).

The check excludes:

* `lib/iris/tests/`
* `docs/gallery_code/`

The section `[tool.numpydoc_validation]` in `pyproject.toml` section defines all the rules to apply - which default to `all` with specific ignores that can be addressed over time.

This PR is based upon the GeoVista implementation https://github.com/bjlittle/geovista/pull/716.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

2024-02-21 14:00 UTC, trexfeathers requested changes

2024-02-21 14:00 UTC, trexfeathers commented on docs/src/further_topics/filtering_warnings.rst
> +    iris/coord_systems.py:770: IrisDefaultingWarning: Discarding false_easting and false_northing that are not used by Cartopy.
```suggestion
      warnings.warn(wmsg, category=iris.warnings.IrisUserWarning)
    iris/coord_systems.py:770: IrisDefaultingWarning: Discarding false_easting and false_northing that are not used by Cartopy.
```

This doctest is supposed to demonstrate the filtering of a warning based on line number. The `IrisUserWarning` is now being generated on line `444`, so a filter with `lineno=442` is not a valid demonstration. The correct fix would be to change to `lineno=444`.

2024-02-21 17:57 UTC, trexfeathers commented on docs/src/further_topics/filtering_warnings.rst
> +    iris/coord_systems.py:770: IrisDefaultingWarning: Discarding false_easting and false_northing that are not used by Cartopy.
Still need to change:

```diff
-    ... warnings.filterwarnings("ignore", module="iris.coord_systems", lineno=442)
+    ... warnings.filterwarnings("ignore", module="iris.coord_systems", lineno=444)
```

Sorry if that wasn't clear in my previous comment.

2024-02-22 16:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SciTools/iris?pullRequest=5762) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SciTools/iris?pullRequest=5762) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SciTools/iris?pullRequest=5762) it.</sub>

2024-02-23 11:57 UTC, trexfeathers approved these changes

2024-02-27 15:50 UTC, bjlittle approved these changes
@tkknight Lovely `pre-commit` addition 🚀 

This will ensure to add some rigor to the docstrings going forwards 🍻

2024-02-27 15:50 UTC, merged