pytest migration of unit.common.metadata.test_CoordMetadata
SciTools/iris pull request #5880
Opened 2024-03-21 14:41 UTC by bjlittle

## 🚀 Pull Request

### Description

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

---
Add any of the below labels to trigger actions on this PR:

- https://github.com/SciTools/iris/labels/benchmark_this

2024-03-22 16:33 UTC, pp-mo requested changes
Couple of glitches, 
plus some almost-automatic improvements that occur in a multiple places.

Perhaps I should fix those myself, combined for your approval in a PR-to-PR ?

2024-03-26 17:40 UTC, bjlittle commented
@pp-mo Thanks. Back to you 👍

2024-03-27 12:42 UTC, pp-mo commented on lib/iris/tests/unit/common/metadata/test_CoordMetadata.py
> +            assert expected, rmetadata.combine(lmetadata)._asdict()
This one still not fixed ?

2024-03-27 12:42 UTC, pp-mo commented
I think you missed a tiny one -- see above.
Otherwise, ready to go now!

2024-03-27 14:33 UTC, pp-mo commented
Thanks @bjlittle for staying the distance on this one !

2024-03-27 14:33 UTC, merged