pytest migration of unit.common.resolve.test_Resolve
SciTools/iris pull request #5882
Opened 2024-03-22 09:06 UTC by bjlittle

## 🚀 Pull Request

### Description

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

---
Add any of the below labels to trigger actions on this PR:

- https://github.com/SciTools/iris/labels/benchmark_this

2024-04-05 17:33 UTC, pp-mo requested changes
OK I've scanned this at last !
I identified just a few tweaks

2024-04-09 12:28 UTC, bjlittle commented
@pp-mo Thanks for the review and wading through this one 💯 

Back to you 👍

2024-04-09 19:58 UTC, merged

2024-04-09 19:58 UTC, pp-mo commented
Thanks @bjlittle -- done. 
That feels good !

2024-04-09 20:16 UTC, bjlittle commented
@pp-mo Thanks, you're a legend 💯