Use tracemalloc for memory measurements.
SciTools/iris pull request #5948
Opened 2024-05-09 14:12 UTC by pp-mo

Addresses https://github.com/SciTools/iris/issues/5947

Replaces the current process RSS ("resident set size") based mechanism.

N.B. this is hard to test, possibly only takes effect when merged ?
@trexfeathers can you advise? I'm a bit vague on this.

2024-05-13 13:21 UTC, stephenworsley requested changes

2024-05-13 13:21 UTC, stephenworsley commented on benchmarks/benchmarks/__init__.py
> +        self._peak_mb = peak_mem * 1.0 / 1024**2
Would this be clearer as `peak_mem * 2**-20`?

2024-05-16 14:37 UTC, stephenworsley approved these changes
After running the benchmarks in #5946, I'm satisfied that tracemalloc gives a more accurate view of memory for more cases than the current set up. It seems like there are still some potential difficulties with memory benchmarking for some parallelisation setups, but I don't believe any more problems are being introduced. Otherwise, I think this PR looks good to go.

2024-05-16 14:47 UTC, merged

2024-05-16 18:15 UTC, pp-mo commented
Thanks @stephenworsley !