Update to `cell_method` parsing
SciTools/iris pull request #6083
Opened 2024-07-24 14:34 UTC by ukmo-ccbunney

## 🚀 Pull Request

### Description
Iris was failing to load some netCDF files due to a malformed `cell_method` attribute, but was throwing this slightly unhelpful error:
```python
File /opt/scitools/conda/deployments/default-2024_02_20/lib/python3.11/site-packages/iris/fileformats/_nc_load_rules/helpers.py:267, in _split_cell_methods(nc_cell_methods)
    265 for ii in range(len(name_start_inds) - 1):
    266     method_indices.append((name_start_inds[ii], name_start_inds[ii + 1]))
--> 267 method_indices.append((name_start_inds[-1], len(nc_cell_methods)))
    269 # Index the string and match against each substring
    270 nc_cell_methods_matches = []

IndexError: list index out of range
```

Inspection of the stack trace reveals it was failing to correctly parse the `cell_method` attribute which was missing a space between the colon separator and time method. I.e.
```
cell_methods = "time:point"
```
rather than:
```
cell_methods = "time: point"
```

This PR makes two changes to the cell method parsing in `fileformats/_nc_load_rules/helpers.py`:
1. In `_split_cell_methods`: If the `cell_methods` attribute cannot be parsed, a `Warning` is issued and the function returns an empty list so cube loading can continue. This is consistent with the behaviour further down the function if a cell method cannot be matched.

2. It also makes the pattern matching a little more lenient by making the space after the colon separator between the `name` and `method` pair optional. The [CF Convention](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch07s03.html#:~:text=To%20describe%20the%20characteristic%20of%20a%20field%20that,words%20of%20the%20form%20%22%20name%3A%20method%20%22.) states that the pairs are "blank-separated list of `name: method` pairs". It _does_ show a space after the colon in the examples it gives, but the [CF Compliance checker ](https://cfchecker.ncas.ac.uk/) is happy with no space after the colon.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

---
Add any of the below labels to trigger actions on this PR:

- fixes: #6082

2024-07-24 14:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SciTools/iris?pullRequest=6083) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SciTools/iris?pullRequest=6083) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SciTools/iris?pullRequest=6083) it.</sub>

2024-07-25 11:09 UTC, ukmo-ccbunney commented
Leaving this one as draft for the moment whilst I address some unit test failures.

2024-07-29 16:25 UTC, ukmo-ccbunney commented
Modified slightly to address some failing unit tests.
All tests passing locally for me now.

2024-09-11 09:45 UTC, trexfeathers commented
From @SciTools/peloton:

Related to #5165.

At the very least there needs to be an informative warning, otherwise what's the point in Iris being strict about CF.

Also, if the CF checker is OK with this, maybe we should be OK with it also? @pp-mo would love your opinion on the CF checker's place in these decisions.

2024-10-09 09:30 UTC, HGWright commented
From @SciTools/peloton we want to accept this as CF-compliant.

2024-10-18 09:27 UTC, ESadek-MO requested changes
Thanks @ukmo-ccbunney, changes all look good to me! I think it's worth just adding a small whatsnew entry for this, then it'll be good to go!

2024-10-18 10:04 UTC, ukmo-ccbunney commented
> Thanks @ukmo-ccbunney, changes all look good to me! I think it's worth just adding a small whatsnew entry for this, then it'll be good to go!

Done.

2024-10-18 10:46 UTC, ESadek-MO requested changes
Wrong PR number!

2024-10-18 10:46 UTC, ESadek-MO commented on docs/src/whatsnew/latest.rst
> +   whitespace. (:pull:`6181`)
```suggestion
   whitespace. (:pull:`6083`)
```

2024-10-18 10:50 UTC, ukmo-ccbunney commented on docs/src/whatsnew/latest.rst
> +   whitespace. (:pull:`6181`)
Whoops! Good spot 🙄

2024-10-18 11:00 UTC, ESadek-MO approved these changes

2024-10-18 11:00 UTC, merged