Proof of concept load performance improvement
SciTools/iris pull request #6088
Opened 2024-07-26 08:04 UTC by stephenworsley

## 🚀 Pull Request

### Description

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

---
Add any of the below labels to trigger actions on this PR:

- https://github.com/SciTools/iris/labels/benchmark_this

2024-07-26 12:33 UTC, pp-mo commented
> Initial [benchmark results](https://github.com/SciTools/iris/pull/6088#issuecomment-2252631900) are interesting. not all straightforward. I'm going to run that again ...

WHOOPS sorry, I did that to the wrong PR

2024-07-29 10:45 UTC, bjlittle requested changes
@stephenworsley Looks good! 💯 

Just a couple of comments to service, then we can bank this 👍

2024-07-29 10:45 UTC, bjlittle commented on lib/iris/fileformats/cf.py
> +        for _, variable in self._dataset.variables.items():
```suggestion
        for variable in self._dataset.variables.values():
```

2024-07-29 10:45 UTC, bjlittle commented on lib/iris/fileformats/netcdf/ugrid_load.py
> +        return {}
@stephenworsley A stylistic thing ... but it's better to only have one `return` from the function. 

So I'd suggest this like this instead:

```python
meshes = {}

if cf_reader._with_ugrid:
    mesh_vars = cf_reader.cf_group.meshes
    meshes = {
        name: _build_mesh(cf_reader, var, cf_reader.filename)
        for name, var in mesh_vars.itesm()
    }

return meshes
```

2024-07-29 13:57 UTC, bjlittle approved these changes

2024-07-29 14:20 UTC, merged