social: migrate from x to bluesky
SciTools/iris pull request #6237
Opened 2024-11-24 00:09 UTC by bjlittle

## 🚀 Pull Request

### Description

This pull-request migrates our social from `X` to `Bluesky` :partying_face: 

Time to join the tech `X`-odus ... but don't take my word for it, checkout the stats [here](https://bsky.jazco.dev/stats) and [here](https://bcounter.nat.vg/).

2025-04-10 13:44 UTC, trexfeathers requested changes
Thanks @bjlittle, sorry for forgetting about this.

I can confirm that there are no remaining references to Twitter in the repository (besides the linkcheck ignore), and that all your changes render as expected.

2025-04-10 13:44 UTC, trexfeathers commented on README.md
>- [ ] Announce migration to https://bsky.app/profile/scitools.bsky.social on `X`

Can we also announce this in a What's New entry?

2025-04-10 13:44 UTC, trexfeathers commented on README.md
>- [ ] Create `SciTools/bluesky-scitools` GH repository

Can I suggest just renaming the existing repository? It has good content in there and none of it is Twitter-specific.

2025-05-12 20:59 UTC, bjlittle commented on README.md
Done. See https://github.com/SciTools/bluesky-scitools

:butterfly:

2025-05-12 21:56 UTC, bjlittle commented on README.md
Done. 

See https://github.com/SciTools/iris/pull/6237/commits/971f548441c43f333798e543014a95c69d2f01ee :+1:

2025-05-12 22:12 UTC, bjlittle commented
Back to you @trexfeathers 👍

2025-05-13 13:15 UTC, trexfeathers approved these changes

2025-05-13 13:17 UTC, merged

2025-05-13 13:28 UTC, bjlittle commented
@trexfeathers Awesome, thanks 🥳