Cache Dask arrays created from `NetCDFDataProxy`s to speed up loading files with multiple variables
SciTools/iris pull request #6252
Opened 2024-12-10 20:36 UTC by bouweandela

## 🚀 Pull Request

### Description

Another idea to speed up loading NetCDF files with many variables. This caches the last 100 Dask arrays created from `NetCDFDataProxy`s so shared coordinates can be re-used. Since copying a Dask array is much faster than creating a new one, this gives a speedup.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

---
Add any of the below labels to trigger actions on this PR:

- https://github.com/SciTools/iris/labels/benchmark_this

2024-12-11 12:14 UTC, pp-mo commented
The benchmarks showing changes aren't really the ones I'd expect.
I'm going to re-spin that ...

2024-12-11 13:11 UTC, bouweandela commented
I added a benchmark in bfbd62551ba52cc09d1667f4c036420f6a12d807 that should show the improvement.

2024-12-11 13:53 UTC, pp-mo commented
> | 808±0.8k

💯 it will be great to see this come together !

2025-02-13 17:26 UTC, ESadek-MO requested changes
Thanks @bouweandela, looks really good to me for the most part!

Only one suggestion, and I'm happy for you to oppose that. Other than that happy for this to be merged.

2025-02-13 21:10 UTC, bouweandela commented on lib/iris/_lazy_data.py
> +CACHE = LRUCache(100)
Thank you for reviewing!

> I wonder if MAX_CACHE_SIZE would be a helpful constant, for easier changing of this in the future

Added in 8d75e1b.

> I assume 100 is somewhat arbitrary at the moment?

There has to be some limit and it seems unlikely that any file will contain more than ~10 or so shared arrays, so 100 seemed like a large enough choice to cover all use cases while keeping the memory use very modest.

2025-02-14 14:30 UTC, ESadek-MO approved these changes
Happy with this, thank you!

2025-02-14 14:31 UTC, merged